"""Getting the in-process telemetry out: OTLP for traces, a scrape endpoint for metrics.

The engine's own tracer is the source of truth and OpenTelemetry is an export
adapter, which is the opposite of the usual arrangement. Three reasons, all of
them things that bite later:

1. Tail sampling needs the whole trace in hand before deciding whether to keep
   it. The OTel SDK's batch processor ships spans as they end, so by the time a
   run turns out to be the expensive one worth keeping, its early spans are
   already gone or already dropped. Buffering locally and exporting at the end
   is what makes "always keep errors" achievable.
2. Cost is not a concept OTel has. Carrying exact `Money` through our own span
   and flattening it to attributes only at export keeps the arithmetic exact and
   keeps a float out of the billing path.
3. Tests. Asserting on real spans without standing up a collector is what makes
   instrumentation regression-testable at all.

Every import of an optional library is local to the function that needs it, so
importing this module on a machine with no OTel installed does nothing worse
than make `OtlpTraceExporter` raise when you actually try to construct one.
"""

from __future__ import annotations

import json
from collections.abc import Iterable
from http.server import BaseHTTPRequestHandler, HTTPServer
from threading import Thread
from typing import Any

from ..core.errors import ConfigurationError
from .metrics import MetricsRegistry
from .trace import Trace

__all__ = ["PROMETHEUS_CONTENT_TYPE", "OtlpTraceExporter", "serve_metrics", "traces_to_jsonl"]

PROMETHEUS_CONTENT_TYPE = "text/plain; version=0.0.4; charset=utf-8"


def traces_to_jsonl(traces: Iterable[Trace]) -> str:
    """Newline-delimited JSON — the zero-infrastructure export.

    Genuinely useful, not a placeholder: a kept trace written to a file is
    greppable, diffable in a PR, and attachable to a bug report. The eval
    harness (P4) stores traces this way so a quality regression can be inspected
    span by span months later without a tracing backend having retained it.
    """
    return "\n".join(json.dumps(t.to_dict(), separators=(",", ":")) for t in traces)


class OtlpTraceExporter:
    """Ships kept traces to an OTLP endpoint, preserving the parent tree.

    Span ids are generated by our `IdFactory` and are not the 8/16-byte integers
    OTel requires, so they are hashed into the right shape deterministically —
    the same omnex id always maps to the same OTel id, which is what lets a
    trace found in Grafana be looked up by its omnex id in the audit trail.
    """

    def __init__(self, endpoint: str, service_name: str = "omnex-engine") -> None:
        if not endpoint:
            raise ConfigurationError("OTLP endpoint is required to construct an exporter")
        self.endpoint = endpoint
        self.service_name = service_name
        self._provider: Any = None

    @staticmethod
    def _otel_id(ident: str, size: int) -> int:
        import hashlib

        digest = hashlib.blake2b(ident.encode(), digest_size=size).digest()
        value = int.from_bytes(digest, "big")
        return value or 1  # zero is reserved as "invalid" in the spec

    def _ensure_provider(self) -> Any:
        if self._provider is not None:
            return self._provider
        try:
            from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
            from opentelemetry.sdk.resources import Resource
            from opentelemetry.sdk.trace import TracerProvider
            from opentelemetry.sdk.trace.export import BatchSpanProcessor
        except ImportError as exc:  # pragma: no cover - exercised only with the extra installed
            raise ConfigurationError(
                "OTLP export needs the 'otel' extra: pip install 'omnex-engine[otel]'"
            ) from exc

        provider = TracerProvider(resource=Resource.create({"service.name": self.service_name}))
        provider.add_span_processor(BatchSpanProcessor(OTLPSpanExporter(endpoint=self.endpoint)))
        self._provider = provider
        return provider

    def export(self, traces: Iterable[Trace]) -> int:
        """Export finished traces. Returns the number of spans shipped."""
        from opentelemetry.trace import SpanContext, TraceFlags, set_span_in_context
        from opentelemetry.trace.span import NonRecordingSpan

        provider = self._ensure_provider()
        tracer = provider.get_tracer("omnex")
        shipped = 0

        for trace in traces:
            trace_id = self._otel_id(trace.trace_id, 16)
            contexts: dict[str, Any] = {}
            # Parents before children, so a child always finds its parent context.
            ordered = sorted(trace.spans, key=lambda s: s.start_mono)
            for span in ordered:
                parent_ctx = contexts.get(span.parent_id or "")
                otel_span = tracer.start_span(
                    span.name,
                    context=parent_ctx,
                    start_time=int(span.started_at.timestamp() * 1e9),
                    attributes=self._attributes(span.to_dict()),
                )
                span_ctx = SpanContext(
                    trace_id=trace_id,
                    span_id=self._otel_id(span.span_id, 8),
                    is_remote=False,
                    trace_flags=TraceFlags(TraceFlags.SAMPLED),
                )
                contexts[span.span_id] = set_span_in_context(NonRecordingSpan(span_ctx))
                if span.status == "error" and span.error:
                    otel_span.set_status(self._error_status(), str(span.error.get("message", "")))
                end_ns = int((span.started_at.timestamp() + (span.duration_seconds or 0.0)) * 1e9)
                otel_span.end(end_time=end_ns)
                shipped += 1

        provider.force_flush()
        return shipped

    @staticmethod
    def _error_status() -> Any:
        from opentelemetry.trace import Status, StatusCode

        return Status(StatusCode.ERROR)

    @staticmethod
    def _attributes(payload: dict[str, Any]) -> dict[str, Any]:
        """Flatten to the scalar types OTel accepts, keeping cost readable.

        `cost_usd` is emitted as a string, not a float. A float here would be the
        one place in the whole pipeline where money loses precision, and it would
        do it in the copy people build dashboards from.
        """
        picos = int(payload.get("cost_picos", 0) or 0)
        flat: dict[str, Any] = {
            "omnex.span_id": payload["span_id"],
            "omnex.trace_id": payload["trace_id"],
            "omnex.kind": payload["kind"],
            "omnex.cost_picodollars": picos,
            "omnex.cost_usd": f"{picos / 1e12:.12f}",
            "omnex.tokens.input": payload.get("input_tokens", 0),
            "omnex.tokens.output": payload.get("output_tokens", 0),
            "omnex.tokens.cached_input": payload.get("cached_input_tokens", 0),
        }
        for key, value in (payload.get("attributes") or {}).items():
            flat[f"omnex.attr.{key}"] = (
                value if isinstance(value, (str, int, float, bool)) else json.dumps(value)
            )
        return flat


def serve_metrics(
    registry: MetricsRegistry, port: int = 9464, host: str = "127.0.0.1"
) -> HTTPServer:
    """Serve `/metrics` on a background thread using only the standard library.

    Returned rather than blocking, so a caller owns the lifetime and a test can
    shut it down. `/healthz` is here too because a scrape target that has no
    liveness endpoint gets one bolted on badly later.
    """

    class Handler(BaseHTTPRequestHandler):
        def do_GET(self) -> None:
            if self.path.startswith("/metrics"):
                body = registry.render().encode()
                self.send_response(200)
                self.send_header("Content-Type", PROMETHEUS_CONTENT_TYPE)
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            elif self.path.startswith("/healthz"):
                self.send_response(200)
                self.end_headers()
                self.wfile.write(b"ok")
            else:
                self.send_response(404)
                self.end_headers()

        def log_message(self, *_: Any) -> None:
            """Silence. A scrape every 15s would otherwise dominate the logs."""

    server = HTTPServer((host, port), Handler)
    Thread(target=server.serve_forever, daemon=True, name="omnex-metrics").start()
    return server
