"""Run every invariant, render the map, fail the build on any breach.

    python scripts/invariant_map.py

The same shape as `ontology_map.py` one level in. That file asks whether every
claim about a BRANCH is backed by code that imports; this asks whether every
rule about the CODE is backed by a predicate that runs.

## The rule about rules

An entry with neither a `checker` nor a stated `unenforceable` reason is itself
a violation. That is the whole anti-Goodhart mechanism here: without it,
`invariants.json` becomes a second copy of CLAUDE.md — a list of good intentions
that renders beautifully and enforces nothing, which is precisely the state this
was built to leave.

So there are three honest outcomes for a rule and only three: it has a predicate
that passes, it has a predicate that fails and the build stops, or somebody has
written down why no predicate is possible. "We mean it" is not among them.

## Why the allowlist carries reasons

`clock_is_injected` has two exceptions and each names the parameter that already
provides injection. An exception with a reason is a boundary; an exception
without one is the rule quietly ending. `branches.json` handles missing work the
same way, and the count of allowlisted files is the number to watch — two that
each name a working escape hatch is a boundary, five vague ones is a rule that
has stopped applying.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

from invariants import CHECKERS, ENGINE, REPO, Violation, load_registry

OUTPUT = ENGINE / "ontology" / "INVARIANTS.md"


def audit_registry(entries: list[dict[str, Any]]) -> list[str]:
    """Problems with the registry itself, before any checker runs."""
    problems: list[str] = []
    seen: set[str] = set()
    for entry in entries:
        ident = str(entry.get("id", ""))
        if not ident:
            problems.append("an entry has no id")
            continue
        if ident in seen:
            problems.append(f"{ident}: listed twice")
        seen.add(ident)

        if not str(entry.get("rule", "")).strip():
            problems.append(f"{ident}: no rule text, so nothing is being claimed")
        if not str(entry.get("paid_for", "")).strip():
            problems.append(
                f"{ident}: no `paid_for` — a rule nobody can point at a failure for is a "
                "preference, and preferences do not belong in a gate"
            )

        checker = entry.get("checker")
        unenforceable = str(entry.get("unenforceable", "")).strip()
        if checker is None and not unenforceable:
            problems.append(
                f"{ident}: no checker and no stated reason one is impossible. Supply a "
                "predicate or say why there cannot be one — this is the rule that stops "
                "the registry becoming a second copy of CLAUDE.md"
            )
        if checker is not None and unenforceable:
            problems.append(f"{ident}: claims to be unenforceable while naming a checker")
        if checker is not None and checker not in CHECKERS:
            problems.append(f"{ident}: names checker {checker!r}, which does not exist")

        for exception in entry.get("allowlist") or []:
            if not str(exception.get("reason", "")).strip():
                problems.append(
                    f"{ident}: allowlists {exception.get('path')!r} with no reason; an "
                    "exception without one is the rule quietly ending"
                )
            path = REPO / str(exception.get("path", ""))
            if not path.exists():
                problems.append(f"{ident}: allowlists {exception.get('path')!r}, which is gone")
    return problems


def run(entries: list[dict[str, Any]]) -> dict[str, list[Violation]]:
    """Every checker, with its own allowlist applied."""
    results: dict[str, list[Violation]] = {}
    for entry in entries:
        checker = entry.get("checker")
        if checker is None:
            continue
        allowlist = tuple(str(e["path"]) for e in entry.get("allowlist") or [])
        function = CHECKERS[str(checker)]
        results[str(entry["id"])] = (
            function(allowlist) if str(checker) == "clock_is_injected" else function()
        )
    return results


def render(entries: list[dict[str, Any]], results: dict[str, list[Violation]]) -> str:
    enforced = [e for e in entries if e.get("checker")]
    declared = [e for e in entries if not e.get("checker")]
    breaches = sum(len(v) for v in results.values())
    exceptions = sum(len(e.get("allowlist") or []) for e in entries)

    lines = [
        "# Invariants — the rules, and whether anything checks them",
        "",
        "Generated by `engine/scripts/invariant_map.py`. Do not edit.",
        "",
        f"**{len(enforced)} of {len(entries)} rules have a predicate that runs.** "
        f"{len(declared)} are declared unenforceable with a reason. "
        f"{breaches} breaches. {exceptions} allowlisted exceptions.",
        "",
        "Before this file existed the answer to *how many of this repository's rules "
        "are checked* was zero, and nobody knew the denominator either. CLAUDE.md "
        "states 31 rules, 21 of them phrased as never/must-not/refuses. Two of the "
        "five defects that prompted this were direct violations of rules written in "
        "that document — greppable in minutes, sitting there because nothing grepped.",
        "",
        "**A rule with no checker and no stated reason fails this script.** That is "
        "the anti-Goodhart mechanism: without it, this file becomes a second copy of "
        "CLAUDE.md that renders beautifully and enforces nothing.",
        "",
        "## Enforced",
        "",
        "| rule | checker | breaches | exceptions |",
        "|---|---|--:|--:|",
    ]
    for entry in enforced:
        found = results.get(str(entry["id"]), [])
        mark = "**" if found else ""
        lines.append(
            f"| `{entry['id']}` | `{entry['checker']}` | {mark}{len(found)}{mark} | "
            f"{len(entry.get('allowlist') or [])} |"
        )

    for entry in enforced:
        lines += ["", f"### `{entry['id']}`", "", str(entry["rule"]), ""]
        lines.append(f"*Paid for by:* {entry['paid_for']}")
        if entry.get("note"):
            lines += ["", str(entry["note"])]
        for exception in entry.get("allowlist") or []:
            lines += ["", f"- **allowed** `{exception['path']}` — {exception['reason']}"]
        found = results.get(str(entry["id"]), [])
        if found:
            lines += ["", "**Breaches:**"]
            lines.extend(f"- `{violation}`" for violation in found)

    lines += [
        "",
        "## Declared unenforceable",
        "",
        "Listed rather than dropped. A rule nobody can check is still a rule, and "
        "hiding it makes the enforced count look better than the repository is.",
        "",
    ]
    for entry in declared:
        lines += [
            f"### `{entry['id']}`",
            "",
            str(entry["rule"]),
            "",
            f"*Why no predicate:* {entry['unenforceable']}",
            "",
        ]
    return "\n".join(lines) + "\n"


def main() -> int:
    entries = load_registry()

    problems = audit_registry(entries)
    if problems:
        print("the registry does not survive its own rules:")
        for problem in problems:
            print(f"  FAIL {problem}")
        return 1

    results = run(entries)
    OUTPUT.write_text(render(entries, results), encoding="utf-8")

    enforced = sum(1 for e in entries if e.get("checker"))
    breaches = sum(len(v) for v in results.values())
    print(f"{enforced} of {len(entries)} rules have a predicate that runs")
    for ident, found in results.items():
        state = f"{len(found)} BREACHES" if found else "ok"
        print(f"  {ident:38} {state}")
        for violation in found:
            print(f"      {violation}")
    print(f"\nwrote {OUTPUT.relative_to(REPO)}")
    return 1 if breaches else 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    raise SystemExit(main())
