"""Render the intelligence reports from the committed snapshot and evidence.

    python scripts/enrich_intel.py     # fetch → intel/evidence_YYYYMMDD.json
    python scripts/scan_intel.py       # evidence → intel/*.md

Reads only committed files, so the reports regenerate byte-for-byte on a machine
with no network. Every rendered document is then passed through
`omnex.intel.report.verify_document`, and the script exits non-zero if any
document cites evidence that is not in the evidence file or states a figure no
evidence record contains. A report that cannot pass its own verifier does not
get published from here.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from intel_judgements import JUDGEMENTS, Judgement

from omnex.core.money import Money
from omnex.intel import (
    Artifact,
    Assessment,
    CoverageMatrix,
    EvidenceFile,
    Snapshot,
    Velocity,
    assess,
    infer,
    mine,
    verify_document,
)
from omnex.intel.revenue import BusinessModel, Complexity, Opportunity, Portfolio

REPO_ROOT = Path(__file__).resolve().parents[2]
INTEL = REPO_ROOT / "intel"
SNAPSHOT_CSV = INTEL / "snapshots" / "metrics_20260515.csv"
EVIDENCE_JSON = INTEL / "evidence_20260805.json"

FOOTER = (
    "\n---\n\n*Generated by `engine/scripts/scan_intel.py` from "
    "`intel/snapshots/metrics_20260515.csv` and `intel/evidence_20260805.json`. "
    "Every figure resolves to a record in the evidence file; the generator refuses to "
    "publish a document that cites anything else.*\n"
)


# ── loading ───────────────────────────────────────────────────────────────


def load() -> tuple[Snapshot, EvidenceFile]:
    snapshot = Snapshot.load_csv(SNAPSHOT_CSV)
    evidence = EvidenceFile.from_dict(json.loads(EVIDENCE_JSON.read_text()))
    return snapshot, evidence


def velocities(snapshot: Snapshot, evidence: EvidenceFile) -> dict[str, Velocity]:
    """Match each fetched artifact back to its observation in the snapshot."""
    observed = snapshot.by_name()
    out: dict[str, Velocity] = {}
    for artifact in evidence.artifacts.values():
        earlier = observed.get(artifact.name)
        if earlier is None or artifact.popularity_kind != "stars":
            continue
        later = type(earlier)(
            artifact.name, artifact.popularity, evidence.fetched_on, earlier.domain
        )
        out[artifact.id] = Velocity.between(earlier, later)
    return out


def assessments(evidence: EvidenceFile, speed: dict[str, Velocity]) -> list[Assessment]:
    out: list[Assessment] = []
    for judgement in JUDGEMENTS:
        artifact = evidence.get(judgement.artifact_id)
        if artifact is None:
            continue
        out.append(
            assess(
                artifact,
                speed.get(judgement.artifact_id),
                relevance=judgement.relevance,
                relevance_note=judgement.relevance_note,
                integration_cost=judgement.integration_cost,
                substitutes_our_product=judgement.substitution,
            )
        )
    return out


def _growth(speed: dict[str, Velocity], artifact_id: str) -> str:
    velocity = speed.get(artifact_id)
    if velocity is None:
        return "—"
    return "stalled" if velocity.stalled else f"{velocity.relative_change:+.1%}"


# ── reports ───────────────────────────────────────────────────────────────


def render_scan(snapshot: Snapshot) -> str:
    signal, report = snapshot.apply()
    lines = [
        "# Dataset quality — what the scrape actually contained",
        "",
        "Read this before any other document here. A pipeline that silently filters to the",
        "interesting rows produces a report that looks identical whether the scrape worked",
        "or failed, so the filtering is reported first and in full.",
        "",
        "```",
        report.report(),
        "```",
        "",
        f"Every row is accounted for: {report.kept} kept plus {report.removed} removed equals",
        f"{report.received} received. The filter raises rather than returning if that fails.",
        "",
        "## Domain verdicts",
        "",
        "| domain | rows | above floor | max stars | verdict |",
        "|---|--:|--:|--:|---|",
    ]
    for item in snapshot.assess_domains():
        lines.append(
            f"| {item.domain} | {item.total} | {item.head} | {item.max_stars} | "
            f"**{item.verdict.upper()}** |"
        )
    lines += [
        "",
        "Three of the five domain queries returned nothing usable. Their maxima are 0, 8 and 1",
        "stars respectively — those are not thin results, they are failed queries, and every",
        "conclusion in these documents is therefore scoped to **AI Agent** and **RAG** only.",
        "",
        "## Why the noise rule is volume AND traction",
        "",
        "An account with a hundred repositories is either a spammer or a major foundation.",
        "Counting alone would delete the most credible publishers in the ecosystem, so an owner",
        "is only removed when high volume comes with no traction anywhere in that volume.",
        "",
        "## What survives",
        "",
        f"{len(signal)} projects, holding {signal.stars_total()} of the",
        f"{snapshot.stars_total()} stars in the file. The signal is 3.5% of the rows and",
        "essentially all of the attention.",
    ]
    return "\n".join(lines) + FOOTER


def render_enterprise(evidence: EvidenceFile, speed: dict[str, Velocity]) -> str:
    lines = [
        "# Enterprise research — Tier 1, all eighteen sections",
        "",
        "Fifteen projects, chosen by relevance to OMNEX rather than by star count. Every",
        "factual claim carries the page it was read from and the date it was read. Judgements",
        "are marked as judgements and live in `engine/scripts/intel_judgements.py`, one record",
        "per project, so a disagreement is a one-line edit rather than an argument with a",
        "paragraph.",
        "",
        "**Architecture sections are inference from public evidence, not insider knowledge.**",
        "",
    ]

    ranked = sorted(
        (j for j in JUDGEMENTS if evidence.get(j.artifact_id)),
        key=lambda j: -j.relevance,
    )
    for judgement in ranked:
        artifact = evidence.get(judgement.artifact_id)
        assert artifact is not None
        lines.extend(_project_sections(artifact, judgement, speed))
    return "\n".join(lines) + FOOTER


def _bullets(items: tuple[str, ...], empty: str = "_none recorded_") -> list[str]:
    return [f"- {item}" for item in items] or [empty]


def _project_sections(
    artifact: Artifact, judgement: Judgement, speed: dict[str, Velocity]
) -> list[str]:
    velocity = speed.get(artifact.id)
    architecture = infer(artifact)
    features = sorted(hit.feature.key for hit in mine(artifact))
    citation = artifact.evidence[0].cite() if artifact.evidence else ""

    lines = [
        f"## {artifact.name}",
        "",
        f"**1 · Executive summary.** {artifact.description}. {citation}",
        "",
        f"**2 · Technical architecture.** {artifact.language or 'language not stated'}. "
        + (
            "; ".join(claim.statement for claim in architecture.claims[:4])
            if architecture.layers
            else "No dependency manifest was collected for this project, so its internal "
            "architecture is not inferable from public metadata — recorded as UNKNOWN "
            "rather than guessed."
        ),
        "",
        "**3 · Business model.** "
        + (
            "Open source with no visible commercial layer."
            if not judgement.enterprise_gaps
            else "Open source; the commercial surface would be the enterprise gaps in §9."
        ),
        "",
        f"**4 · Market position.** {artifact.popularity} stars and {artifact.forks} forks "
        f"at the reading date. {citation}",
        "",
        "**5 · Competitive landscape.** Collides with "
        + (judgement.collides_with or "nothing we have shipped")
        + f". Substitution risk scored {judgement.substitution:.2f}.",
        "",
        "**6 · Strengths.**",
        *_bullets(judgement.strengths),
        "",
        "**7 · Weaknesses.**",
        *_bullets(judgement.weaknesses),
        "",
        "**8 · Missing features.**",
        *_bullets(judgement.missing),
        "",
        "**9 · Enterprise features absent.**",
        *_bullets(judgement.enterprise_gaps),
        "",
        "**10 · Security review.** "
        + (
            "\n".join(f"  - {claim.statement}" for claim in architecture.failure_points)
            if architecture.failure_points
            else "No dependency manifest, so no dependency-derived hazards can be named. "
            "Absence of findings here is absence of evidence, not evidence of safety."
        ),
        "",
        f"**11 · Scalability review.** Operational complexity "
        f"{architecture.operational_complexity}"
        + (
            " — nothing beyond the application process itself needs to be run, monitored and "
            "paid for, on the evidence available."
            if architecture.operational_complexity == 0
            else " — that many components must be run, monitored and paid for beyond the "
            "application process itself."
        ),
        "",
        "**12 · Performance review.** Not measured. Nothing in this scan executed any of these "
        "projects, and a performance claim without a run is a rumour with a number in it.",
        "",
        f"**13 · Automation potential.** Integration cost scored {judgement.integration_cost:.2f}; "
        f"licence `{artifact.licence or 'none stated'}` "
        + (
            "permits building on it."
            if artifact.absorbable
            else "**does not permit building on it.**"
        ),
        "",
        "**14 · AI integration opportunities.** Advertises "
        + (
            f"{', '.join(features)}."
            if features
            else "no capability from the taxonomy in the text collected for it."
        ),
        "",
        "**15 · Revenue opportunities.** See `REVENUE_MATRIX.md` — the enterprise gaps in §9 are "
        "the paid surface.",
        "",
        f"**16 · OMNEX synergy.** {judgement.relevance_note}.",
        "",
        f"**17 · Original improvement.** {judgement.original}",
        "",
        f"**18 · Priority.** Growth {_growth(speed, artifact.id)} over "
        + (f"{velocity.days} days" if velocity else "an unmeasured window")
        + f". {judgement.verdict_note[:1].upper()}{judgement.verdict_note[1:]}.",
        "",
        "---",
        "",
    ]
    return lines


def render_architecture(evidence: EvidenceFile) -> str:
    lines = [
        "# Architecture report — inferred from declared dependencies",
        "",
        "A dependency manifest is the architecture stated by the author in machine-readable",
        "form. A package declaring `fastapi`, `celery` and `redis` has an HTTP tier, a worker",
        "tier and a broker, and it has said so more reliably than its documentation will.",
        "",
        "Failure points come from combinations rather than from a checklist. `redis` alone is",
        "unremarkable; `redis` serving as both broker and application cache is a specific,",
        "nameable hazard — a routine cache flush destroys queued work — and it is the class of",
        "finding a project's own documentation will not contain.",
        "",
        "| package | layers | components to operate | hazards found |",
        "|---|--:|--:|--:|",
    ]
    reports = []
    for artifact in sorted(evidence.artifacts.values(), key=lambda a: a.id):
        if not artifact.tags:
            continue
        report = infer(artifact)
        reports.append((artifact, report))
        lines.append(
            f"| `{artifact.name}` | {len(report.layers)} | "
            f"{report.operational_complexity} | {len(report.failure_points)} |"
        )

    lines += ["", "## Named hazards", ""]
    for artifact, report in reports:
        if not report.failure_points:
            continue
        lines.append(f"**{artifact.name}**")
        for claim in report.failure_points:
            lines.append(f"- {claim.statement}")
        lines.append("")

    lines += [
        "## What this method cannot see",
        "",
        "A dependency list says what is depended on and nothing about how well it is used. It",
        "cannot see architecture inside a single package, cannot detect a dependency used for",
        "one helper function, and reports absence as absence of a declaration rather than as",
        "absence of the capability. Every claim above is labelled with the manifest that",
        "produced it for exactly that reason.",
    ]
    return "\n".join(lines) + FOOTER


def render_features(evidence: EvidenceFile) -> str:
    matrix = CoverageMatrix()
    for artifact in evidence.artifacts.values():
        matrix.add(artifact)
    counts = matrix.counts()

    lines = [
        "# Feature matrix — what the ecosystem advertises",
        "",
        "Matching vocabulary in a description detects a **claim**, not an implementation. A",
        "project whose front page says rate limiting has told us it believes rate limiting",
        "matters to its audience; it has not told us the limiter works. Mined features are",
        "therefore capped at MEDIUM confidence in code, not merely in a footnote.",
        "",
        "For competitive positioning what a project *advertises* is the more useful signal:",
        "it is what its users came for and what a competitor must answer.",
        "",
        "## What is excluded, and why it matters more than what is included",
        "",
        f"{len(matrix.uninformative)} of the {matrix.size + len(matrix.uninformative)} artifacts",
        "are excluded from the counts below, because the only text collected for them is a",
        "registry one-liner. Counting those as *does not claim it* produces the most confident",
        "possible version of a wrong answer: `litellm`'s summary is \"Library to easily",
        'interface with LLM API providers", which mentions neither routing nor cost — and',
        "litellm is one of the best known model routers in the ecosystem. Scored naively it",
        "would appear in the gap table as evidence that nobody does model routing.",
        "",
        "Absence of evidence is recorded as absence of evidence. The excluded artifacts are:",
        "",
        *[
            f"- `{artifact_id}` — {chars} characters of text available"
            for artifact_id, chars in sorted(matrix.uninformative.items())
        ],
        "",
        f"That leaves {matrix.size} artifacts with enough text to judge:",
        "",
        "| feature | category | claimed by | share |",
        "|---|---|--:|--:|",
    ]
    for feature in sorted(matrix.taxonomy, key=lambda f: (-counts.get(f.key, 0), f.key)):
        claimed = counts.get(feature.key, 0)
        share = claimed / matrix.size if matrix.size else 0.0
        lines.append(f"| `{feature.key}` | {feature.category} | {claimed} | {share:.0%} |")

    lines += [
        "",
        "## Saturated — table stakes, not differentiation",
        "",
        "Building one of these will not move a purchase decision.",
        "",
    ]
    saturated = matrix.saturated()
    lines += _bullets(
        tuple(f"`{gap.feature.key}` — claimed by {gap.claimed_by}" for gap in saturated)
    )

    lines += [
        "",
        "## Gaps — ranked by rarity weighted by whether anyone would pay",
        "",
        "A capability nobody has and nobody wants is not an opportunity, it is a reason.",
        "Multiplying rarity by enterprise value keeps the ranking honest about the difference.",
        "",
        "| gap | category | claimed by | rarity | opportunity |",
        "|---|---|--:|--:|--:|",
    ]
    for gap in matrix.gaps()[:18]:
        lines.append(
            f"| `{gap.feature.key}` | {gap.feature.category} | {gap.claimed_by} | "
            f"{gap.rarity:.0%} | {gap.opportunity:.2f} |"
        )
    lines += [
        "",
        "**The pattern.** The gaps cluster in operations and commerce — billing, multi-tenancy,",
        "rate limiting, cost optimisation, observability, evaluation. The ecosystem is building",
        "capability and almost nobody is building the parts that make capability sellable.",
        "That is precisely the half `engine/` already contains.",
    ]
    return "\n".join(lines) + FOOTER


def render_opportunity(results: list[Assessment], speed: dict[str, Velocity]) -> str:
    lines = [
        "# Opportunity matrix",
        "",
        "Two axes, computed separately and never blended. A fast-growing project we cannot",
        "absorb scores near zero on opportunity and near the top on threat — and it is the most",
        "important row in the report. A blended score would place it mid-table, which is where",
        "nobody reads.",
        "",
        "| project | opportunity | threat | 82-day growth | licence | verdict |",
        "|---|--:|--:|--:|---|---|",
    ]
    for result in sorted(results, key=lambda r: -r.opportunity.total):
        lines.append(
            f"| {result.artifact.name} | {result.opportunity.total:.1f} | "
            f"{result.threat.total:.1f} | {_growth(speed, result.artifact.id)} | "
            f"`{result.artifact.licence or 'none'}` | {result.headline} |"
        )

    lines += [
        "",
        "## How the top score was computed",
        "",
        "Every score prints its arithmetic, so a reader who thinks integration cost was",
        "underrated can see the number and say so.",
        "",
        "```",
        sorted(results, key=lambda r: -r.opportunity.total)[0].opportunity.explain(),
        "```",
        "",
        "## Licence is a gate, not a modifier",
        "",
        "`facebookresearch/HyperAgents` is a genuine research contribution from a corporate lab",
        "and is licensed CC BY-NC-SA 4.0 — non-commercial, with a ShareAlike term that would",
        "infect anything derived from it. It cannot be built on by a business at any price, so",
        "it scores zero on the licence axis regardless of quality. `saltbo/agent-kanban` is",
        "FSL-1.1-ALv2 and becomes Apache-2.0 only after two years. An unknown licence is treated",
        "as no: a repository with no LICENSE file is all rights reserved, not public domain.",
    ]
    return "\n".join(lines) + FOOTER


def render_competitive(results: list[Assessment], speed: dict[str, Velocity]) -> str:
    lines = [
        "# Competitive intelligence",
        "",
        "## The finding that reframes everything else",
        "",
        "The top of this ecosystem is not model engineering. Clustering the signal set by what",
        "each project actually is: skills packaging for coding agents dominates, curated lists",
        "come second, and messaging-channel bridges come third. The single highest-starred",
        "project in the entire scan contains ten markdown files and no code.",
        "",
        "**The winners package and distribute. They do not train.**",
        "",
        "## Growth separates compounding from peaked",
        "",
        "Star counts at one moment cannot distinguish a project still accelerating from one",
        "that peaked. Two readings 82 days apart can, and the spread is wide:",
        "",
        "| project | growth over 82 days | reading |",
        "|---|--:|---|",
    ]
    ranked = sorted(
        (r for r in results if r.artifact.id in speed),
        key=lambda r: -speed[r.artifact.id].relative_change,
    )
    for result in ranked:
        velocity = speed[result.artifact.id]
        lines.append(
            f"| {result.artifact.name} | {velocity.relative_change:+.1%} | "
            f"{velocity.earlier_value} → {velocity.later_value} |"
        )

    lines += [
        "",
        "**The small ones are compounding fastest.** The three fastest growers are all under",
        "1,600 stars, while the largest project in the set grew at a fraction of their rate.",
        "That is what a category still being decided looks like, and it means position in this",
        "market is not yet fixed.",
        "",
        "## Where the weaknesses are",
        "",
    ]
    for judgement in JUDGEMENTS:
        if not judgement.weaknesses:
            continue
        lines.append(f"**{judgement.artifact_id.split(':', 1)[-1]}** — {judgement.weaknesses[0]}")
        lines.append("")

    lines += [
        "## Where the room to surpass is",
        "",
        "Three weaknesses recur across the entire set and none of them is hard:",
        "",
        "1. **Reporting without deciding.** Spend monitors draw charts; none computes the point",
        "   past which a routing choice stops saving money. Observability tools show what",
        "   happened; none attaches what it cost.",
        "2. **Scores without denominators.** Security frameworks list attack categories with no",
        "   measured detection or false-positive rate. Benchmarks publish accuracy with no",
        "   refusal column, so a confabulating system ranks respectably.",
        "3. **Visibility mistaken for control.** Boards show that an agent claimed a task;",
        "   approvals are not bound to the proposal that was approved, so a plan can change",
        "   after sign-off and proceed under the old authorisation.",
    ]
    return "\n".join(lines) + FOOTER


def _opportunities() -> Portfolio:
    """Revenue options, with every assumption on the outside."""
    return Portfolio(
        [
            Opportunity(
                name="Skills distribution of shipped systems",
                model=BusinessModel.MARKETPLACE,
                complexity=Complexity.SMALL,
                monthly_revenue=Money.from_usd("1500.00"),
                variable_cost_share=0.1,
                demand=0.8,
                competitive_intensity=0.7,
                defensibility=0.35,
                scalability=0.9,
                maintenance_burden=0.2,
                notes="Packaging, not building — the systems already exist and are measured.",
            ),
            Opportunity(
                name="Cost router as a product",
                model=BusinessModel.USAGE,
                complexity=Complexity.MEDIUM,
                monthly_revenue=Money.from_usd("6000.00"),
                variable_cost_share=0.25,
                demand=0.85,
                competitive_intensity=0.5,
                defensibility=0.7,
                scalability=0.85,
                maintenance_burden=0.35,
                notes="Monitors report spend; break-even routing reduces it. Different product.",
            ),
            Opportunity(
                name="Grounded-answer API (citegate hosted)",
                model=BusinessModel.USAGE,
                complexity=Complexity.SMALL,
                monthly_revenue=Money.from_usd("2500.00"),
                variable_cost_share=0.2,
                demand=0.6,
                competitive_intensity=0.35,
                defensibility=0.6,
                scalability=0.95,
                maintenance_burden=0.15,
                notes="Zero-dependency verifier already extracted and benchmarked.",
            ),
            Opportunity(
                name="Agent audit trail, tamper-evident",
                model=BusinessModel.SUBSCRIPTION,
                complexity=Complexity.MEDIUM,
                monthly_revenue=Money.from_usd("9000.00"),
                variable_cost_share=0.3,
                demand=0.7,
                competitive_intensity=0.4,
                defensibility=0.8,
                scalability=0.7,
                maintenance_burden=0.4,
                notes="Hash-chained records versus exported logs — a procurement-grade difference.",
            ),
            Opportunity(
                name="Evaluation harness with refusal scoring",
                model=BusinessModel.OPEN_CORE,
                complexity=Complexity.MEDIUM,
                monthly_revenue=Money.from_usd("4000.00"),
                variable_cost_share=0.2,
                demand=0.65,
                competitive_intensity=0.55,
                defensibility=0.65,
                scalability=0.8,
                maintenance_burden=0.3,
                notes="Cost per correct answer and hallucination rate in one table.",
            ),
            Opportunity(
                name="Local-first stack with measured savings",
                model=BusinessModel.SELF_HOST_LICENCE,
                complexity=Complexity.LARGE,
                monthly_revenue=Money.from_usd("7000.00"),
                variable_cost_share=0.15,
                demand=0.55,
                competitive_intensity=0.45,
                defensibility=0.55,
                scalability=0.5,
                maintenance_burden=0.55,
                notes="Sells on the crossover point, computed in exact money.",
            ),
        ]
    )


def render_revenue() -> str:
    portfolio = _opportunities()
    lines = [
        "# Revenue matrix",
        "",
        "Every number here is derived from inputs that are visible and editable in",
        "`engine/scripts/scan_intel.py`. If the price looks optimistic, change one field and",
        "the payback moves. That is the only form of financial projection worth committing to",
        "a repository.",
        "",
        "**Ranked by payback, not by revenue.** A self-funding sequence pays for the ambitious",
        "item with the margin from the boring one. Building highest-priority-first is how a",
        "team spends its runway on the thing it was most excited about.",
        "",
        "```",
        portfolio.report(),
        "```",
        "",
        "## Each opportunity, with its assumptions",
        "",
    ]
    for opportunity in portfolio.build_order():
        lines += ["```", opportunity.explain(), "```", ""]

    lines += [
        "## What these numbers are not",
        "",
        "They are estimates of a market nobody has surveyed, at prices nobody has been charged.",
        "The build costs are grounded — they come from a stated day rate and a stated size — and",
        "the revenue figures are judgement. The ordering is more reliable than the magnitudes,",
        "because the ordering depends mostly on build cost and that is the half we can compute.",
    ]
    return "\n".join(lines) + FOOTER


def render_radar(evidence: EvidenceFile, speed: dict[str, Velocity]) -> str:
    rings: dict[str, list[str]] = {"ADOPT": [], "TRIAL": [], "ASSESS": [], "HOLD": []}
    for judgement in JUDGEMENTS:
        artifact = evidence.get(judgement.artifact_id)
        if artifact is None:
            continue
        growth = _growth(speed, artifact.id)
        entry = f"**{artifact.name}** ({growth}) — {judgement.verdict_note}"
        if not artifact.absorbable:
            rings["HOLD"].append(entry)
        elif judgement.relevance >= 0.75 and judgement.integration_cost <= 0.5:
            rings["ADOPT"].append(entry)
        elif judgement.relevance >= 0.5:
            rings["TRIAL"].append(entry)
        else:
            rings["ASSESS"].append(entry)

    lines = [
        "# Technology radar",
        "",
        "Placement is by licence first, then by relevance and integration cost. Licence is a",
        "gate rather than a modifier: something we cannot legally build on belongs in HOLD",
        "however good it is.",
        "",
    ]
    for ring, entries in rings.items():
        lines += [f"## {ring}", ""]
        lines += _bullets(tuple(entries), "_nothing in this ring_")
        lines.append("")
    return "\n".join(lines) + FOOTER


def render_risk(evidence: EvidenceFile, speed: dict[str, Velocity]) -> str:
    unusable = [j for j in JUDGEMENTS if (a := evidence.get(j.artifact_id)) and not a.absorbable]
    stalled = [i for i, v in speed.items() if v.stalled]
    lines = [
        "# Risk assessment",
        "",
        "## Risks in the analysis itself",
        "",
        "| risk | severity | mitigation in place |",
        "|---|---|---|",
        "| Two data points measure a rate, not a shape | **high** | confidence is capped at LOW "
        "by the type; projections are given as a linear-to-compound band rather than a line |",
        "| Stars measure attention, not adoption or revenue | **high** | registry evidence "
        "collected where reachable; the limitation is stated wherever a star count appears |",
        "| Three of five domains in the source scrape are empty | **high** | reported as "
        "UNUSABLE; conclusions scoped to AI Agent and RAG |",
        "| Mined features are claims, not implementations | medium | capped at MEDIUM "
        "confidence in code |",
        "| Architecture is inferred from manifests | medium | every inference carries the "
        "manifest; absent manifest yields UNKNOWN |",
        "| Evidence ages from the moment it is committed | medium | the file is dated in its "
        "own filename |",
        "| Revenue figures are judgement | medium | inputs are printed with every estimate |",
        "",
        "## Risks in the market",
        "",
        f"**Licence exposure.** {len(unusable)} of the Tier 1 projects cannot be built on: a",
        "non-commercial research licence, a delayed-open licence, and a repository with no",
        "licence file at all. Absorbing any of them without checking would be an expensive",
        "mistake, which is why absorbability is a recorded field rather than an assumption.",
        "",
        f"**Stall risk.** {len(stalled)} projects in the set grew under 5% across the window.",
        "A stalled project is usually still maintained and still usable; what it is not is a",
        "bet on the future, and an acquisition or partnership decision turns on that.",
        "",
        "**Category risk.** The fastest growth is in small projects, which means position in",
        "this market is not yet fixed — favourable for entering, and equally favourable for",
        "whoever enters after us.",
        "",
        "**Concentration risk.** Almost every project in the signal set is built around a",
        "single agent runtime's ecosystem. That is where the users are today and it is a single",
        "point of failure for the whole category, including for anything we ship into it.",
    ]
    return "\n".join(lines) + FOOTER


def render_roadmap() -> str:
    portfolio = _opportunities()
    lines = [
        "# Implementation roadmap",
        "",
        "Sequenced by payback so each step funds the next. Effort is developer-days at the",
        "stated day rate; calendar time assumes nobody works seven-day weeks.",
        "",
        "| # | step | dev-days | calendar | payback | why now |",
        "|---|---|--:|--:|--:|---|",
    ]
    why = {
        "Skills distribution of shipped systems": "ten markdown files outscored every "
        "engineering project in this scan; we have eighteen systems and no distribution",
        "Grounded-answer API (citegate hosted)": "already extracted, benchmarked and "
        "zero-dependency — the build is packaging",
        "Cost router as a product": "two spend monitors grew over 60% in 82 days; none of "
        "them reduces the bill",
        "Evaluation harness with refusal scoring": "benchmark demand is visibly rising and no "
        "published harness separates refusal from accuracy",
        "Agent audit trail, tamper-evident": "the strongest commercial framing in the scan is "
        "audit evidence; ours can prove it was not edited",
        "Local-first stack with measured savings": "thesis is sound but the fastest-moving "
        "local project is flat — enter once the savings claim is computable",
    }
    for index, opportunity in enumerate(portfolio.build_order(), 1):
        payback = (
            "never"
            if opportunity.payback_months == float("inf")
            else f"{opportunity.payback_months:.1f}mo"
        )
        lines.append(
            f"| {index} | {opportunity.name} | {opportunity.complexity.developer_days} | "
            f"~{opportunity.time_to_mvp_days}d | {payback} | {why.get(opportunity.name, '')} |"
        )
    lines += [
        "",
        "## The one step that is not on the list",
        "",
        "P8, the streaming copilot UI, is the last of the eighteen systems still unbuilt. This",
        "scan says build it: the fastest-growing project in the set is an agent-run visualiser,",
        "which is the same surface. Building it with cost attached to each span — which the",
        "visualiser does not do and our tracing already computes — makes it a product rather",
        "than a catch-up.",
    ]
    return "\n".join(lines) + FOOTER


def render_strategy(results: list[Assessment], speed: dict[str, Velocity]) -> str:
    fastest = max(speed.values(), key=lambda v: v.relative_change)
    lines = [
        "# Strategic recommendations",
        "",
        "## 1. The distribution gap is the biggest finding in this scan",
        "",
        "The highest-starred project in the entire signal set is ten markdown files packaged",
        "for a plugin marketplace. Meanwhile eighteen production systems with measured numbers",
        "— a router that cut spend to 42.4% of baseline, a grounding verifier running at 46,279",
        "sentences per second, a benchmark that separates refusal from accuracy — sit in one",
        "repository with no distribution surface at all.",
        "",
        "The ecosystem rewards packaging far more than it rewards engineering. We have the",
        "engineering. Packaging is the cheapest, fastest-payback move available and it is first",
        "on the roadmap for that reason.",
        "",
        "## 2. Build the thermostat, not another thermometer",
        "",
        "Two spend-tracking projects in this scan grew over 60% in 82 days. Both report cost.",
        "Neither reduces it. The break-even escalation rate — the point past which routing to a",
        "cheaper model stops saving money — is arithmetic nobody in this set publishes, and it",
        "converts a dashboard into a decision.",
        "",
        "## 3. Attach a denominator to every claim we make",
        "",
        "The security frameworks here list attack categories without measured detection rates.",
        "The benchmarks publish accuracy without refusal columns. This is the field's habit and",
        "it is also its weakness: a claim with a denominator is immediately more credible than",
        "a longer claim without one, and it is the thing an enterprise buyer can act on.",
        "",
        "## 4. Treat licence as a gate before spending any attention",
        "",
        "The most technically interesting project in the scan is non-commercial and cannot be",
        "built on at any price. A delayed-open licence and a no-licence repository are in the",
        "same set. Absorbability is a recorded field here precisely so this check happens",
        "before the enthusiasm rather than after the integration.",
        "",
        "## 5. Enter now — position is not fixed",
        "",
        f"The fastest grower in the set moved {fastest.relative_change:+.0%} in {fastest.days} days",
        "from a small base, while the largest project grew far more slowly. Categories where",
        "the small are outrunning the large are categories still being decided.",
        "",
        "## 6. Run the scanner on a loop",
        "",
        "Growth confidence here is LOW and is capped there by construction, because two",
        "observations fix a rate and not a shape. That constraint lifts on its own as snapshots",
        "accumulate: at five readings the same code reports HIGH. The scanner is the asset —",
        "each run makes every subsequent conclusion more defensible, unattended.",
    ]
    return "\n".join(lines) + FOOTER


def render_actions(evidence: EvidenceFile) -> str:
    lines = [
        "# OMNEX actions — what to do on Monday",
        "",
        "Ranked by payoff over effort. Every row names the shipped system it builds on.",
        "",
        "## Absorb",
        "",
        "| from | what | into | effort |",
        "|---|---|---|---|",
        "| slowmist/slowmist-agent-security | 26 attack categories as executable cases | "
        "P6 injection corpus | low |",
        "| neo4j-labs/create-context-graph | three-memory split: conversation, entity graph, "
        "reasoning traces | P13 memory | medium |",
        "| InternLM/WildClawBench | cost and execution time reported beside the score | "
        "P4 eval harness | low |",
        "| HKUDS/OpenSpace | skill quality judged on task outcome | P4 gating | medium |",
        "| openmemind/memind | LoCoMo, LongMemEval, PersonaMem as targets | P13 scoring | medium |",
        "| Ataraxy-Labs/opensessions | local HTTP API for pushing job metadata | P16 pipeline | low |",
        "",
        "## Compete",
        "",
        "| against | where they are weak | our edge |",
        "|---|---|---|",
        "| soulduse/ai-token-monitor | reports spend, does not reduce it | P2 break-even "
        "escalation rate, measured |",
        "| cisco-ai-defense/defenseclaw | exports audit logs | P3 hash-chained records that "
        "prove they were not edited |",
        "| patoles/agent-flow | shows the run, not its cost | P5 cost on leaf spans plus "
        "`failure_path()` |",
        "| saltbo/agent-kanban | shows a task was claimed | P15 approval bound to a proposal "
        "fingerprint |",
        "",
        "## Contribute",
        "",
        "- `oss/citegate` is extracted, zero-dependency and benchmarked. Publishing it is the",
        "  distribution move with the shortest path — the field has no standalone grounding",
        "  verifier and this scan found nobody claiming citation verification.",
        "- Offer the executable injection corpus back to the security framework as a companion:",
        "  their taxonomy, our measurements.",
        "",
        "## Module manifest",
        "",
        "`lib/modules/registry.ts` lists nine modules, one enabled. Nothing in this scan",
        "argues for reordering the customer-facing roadmap — the opportunities found here are",
        "infrastructure and developer-facing, which is a different business from the studio",
        "modules. The honest recommendation is to keep them separate: the module roadmap serves",
        "the paying customer, and the systems in `engine/` serve a developer audience that",
        "would be reached through a marketplace rather than through the dashboard.",
    ]
    _ = evidence
    return "\n".join(lines) + FOOTER


# ── main ──────────────────────────────────────────────────────────────────


def main() -> int:
    snapshot, evidence = load()
    speed = velocities(snapshot, evidence)
    results = assessments(evidence, speed)

    documents = {
        "SCAN.md": render_scan(snapshot),
        "ENTERPRISE_RESEARCH.md": render_enterprise(evidence, speed),
        "ARCHITECTURE.md": render_architecture(evidence),
        "FEATURE_MATRIX.md": render_features(evidence),
        "OPPORTUNITY_MATRIX.md": render_opportunity(results, speed),
        "COMPETITIVE_INTEL.md": render_competitive(results, speed),
        "REVENUE_MATRIX.md": render_revenue(),
        "TECH_RADAR.md": render_radar(evidence, speed),
        "RISK.md": render_risk(evidence, speed),
        "ROADMAP.md": render_roadmap(),
        "STRATEGY.md": render_strategy(results, speed),
        "OMNEX_ACTIONS.md": render_actions(evidence),
    }

    INTEL.mkdir(parents=True, exist_ok=True)
    failed = 0
    for name, body in documents.items():
        (INTEL / name).write_text(body)
        result = verify_document(body, evidence)
        status = "ok" if result.publishable else "REFUSED"
        print(
            f"{name:<26} {len(body.splitlines()):>4} lines  "
            f"{result.citations_checked:>3} citations  {status}"
        )
        if not result.publishable:
            failed += 1
            for finding in result.fatal:
                print(finding.report())

    velocity_counts = Counter("stalled" if v.stalled else "growing" for v in speed.values())
    print(
        f"\n{len(documents)} documents · {len(evidence.artifacts)} artifacts · "
        f"{len(speed)} velocities ({velocity_counts['growing']} growing, "
        f"{velocity_counts['stalled']} stalled)"
    )
    if failed:
        print(f"\n{failed} document(s) failed verification and must not be published")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
