#!/usr/bin/env node
/**
 * Pack generator — premium empty product-photography BACKGROUND scenes.
 *
 * Product decision: these are empty styled surfaces (marble podium, wet glass,
 * linen) with centred copy space, so a buyer composites their own product in.
 * That is a proven Etsy category ("product photography backgrounds") and it is
 * honest — the buyer knows exactly what they get.
 *
 * Deterministic names (scene-NNN.png), retry on failure, and a manifest.json
 * beside each pack logging the exact prompt + seed per file, so a render can be
 * reproduced or a bad one regenerated by seed.
 *
 * Free (Pollinations), remote API — no local GPU load.
 */
import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const OUT = resolve(process.cwd())
const CRAFT = 'centered empty space for product placement, no product, no text, no watermark, soft realistic shadows, commercial studio photography, sharp focus, high detail, photorealistic'

// Format set — the four a buyer actually publishes to.
const FORMATS = { square: [1024, 1024], portrait: [1024, 1280], story: [896, 1568], wide: [1536, 864] }

const PACKS = {
  cosmetics: {
    name: 'Luxury Cosmetics Backgrounds',
    scenes: [
      'empty polished white marble podium, soft diffused daylight from the left, warm neutral background, gentle shadow',
      'empty wet glass surface with fine water droplets and light caustics, cool clean lighting, pale blue-grey gradient background',
      'empty rumpled natural linen cloth, warm late-afternoon window light, soft window-frame shadows, airy off-white background',
      'empty pale stone surface with fresh green botanical leaves and eucalyptus, bright natural daylight, clean airy background',
      'empty champagne silk fabric drape, soft diffused light with a bright reflector, warm neutral background',
      'empty frosted glass shelf, soft pastel peach gradient background, bright even beauty lighting',
      'empty cream travertine stone pedestal, warm directional sunlight, long soft shadow, sand-toned background',
      'empty round mirror base with soft reflections, cool clinical lighting, white gradient background',
      'empty smooth beige clay platform, minimal warm light, terracotta gradient background, spa mood',
      'empty water surface with gentle ripples and soft caustics, bright top light, pale aqua background',
    ],
  },
}

async function fetchImage(prompt, w, h, seed, tries = 4) {
  const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=${w}&height=${h}&model=flux&nologo=true&seed=${seed}`
  for (let t = 1; t <= tries; t++) {
    try {
      const r = await fetch(url, { signal: AbortSignal.timeout(150000) })
      if (!r.ok) throw new Error(`HTTP ${r.status}`)
      const ct = r.headers.get('content-type') ?? ''
      if (!ct.startsWith('image/')) throw new Error(`ct=${ct}`)
      const buf = Buffer.from(await r.arrayBuffer())
      if (buf.length < 8000) throw new Error(`too small ${buf.length}b`)
      return buf
    } catch (e) {
      if (t === tries) throw e
      await new Promise((r) => setTimeout(r, 2500 * t))
    }
  }
}

const packId = process.argv[2] || 'cosmetics'
const pack = PACKS[packId]
if (!pack) { console.error('unknown pack:', packId); process.exit(1) }

const dir = resolve(OUT, packId, 'images')
mkdirSync(dir, { recursive: true })
const manifest = { pack: packId, name: pack.name, generated_at: new Date().toISOString(), images: [] }

// Primary formats for a background pack: square + portrait (most product listings).
const formatPlan = [['square', 'square'], ['portrait', 'portrait']]
let n = 0
for (const [fmtKey] of formatPlan) {
  const [w, h] = FORMATS[fmtKey]
  for (let s = 0; s < pack.scenes.length; s++) {
    n++
    const seed = 1000 + s * 7 + (fmtKey === 'portrait' ? 500 : 0)
    const prompt = `professional product photography background scene, ${pack.scenes[s]}, ${CRAFT}`
    const file = `scene-${String(n).padStart(3, '0')}.png`
    try {
      const buf = await fetchImage(prompt, w, h, seed)
      writeFileSync(resolve(dir, file), buf)
      manifest.images.push({ file, format: fmtKey, w, h, seed, kb: Math.round(buf.length / 1024), prompt })
      console.log(`${file}  ${fmtKey} ${w}x${h}  ${Math.round(buf.length / 1024)}KB`)
    } catch (e) {
      console.log(`${file}  FAILED  ${e.message}`)
      manifest.images.push({ file, format: fmtKey, seed, failed: String(e.message) })
    }
  }
}

writeFileSync(resolve(OUT, packId, 'manifest.json'), JSON.stringify(manifest, null, 2))
const ok = manifest.images.filter((i) => !i.failed).length
console.log(`\n=== ${packId}: ${ok}/${manifest.images.length} OK -> ${packId}/ ===`)
