"""
Expand a character spec into a jobs file for flux_local.py.

The point of this file is one rule, taken from the reverse-engineered blueprints
and confirmed by our own failures: FACE_LOCK and BODY_SPEC go into every prompt
VERBATIM. Locking only the face let the physique be reinvented shot to shot, which
is exactly why the build drifted. Only framing, styling and location vary.

  python mkjobs.py characters/seraphinne.json > jobs-seraphinne.txt
  docker run ... omnex/flux:1 python flux_local.py --jobs jobs-seraphinne.txt --out out
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def build(spec: dict) -> list[str]:
    face = spec["face_lock"].strip()
    body = spec["body_spec"].strip()
    craft = spec["craft"].strip()

    lines = [
        f"# {spec['name']} — generated by mkjobs.py, do not hand-edit",
        f"# FACE_LOCK and BODY_SPEC are identical in every line below. That is the point.",
    ]
    for shot in spec["shots"]:
        prompt = (
            f"{shot['framing']} of a {body}, "
            f"{face}, "
            f"{shot['styling']}, "
            f"{shot['location']}, "
            f"{craft}"
        )
        # The jobs format is name | WxH | count | prompt, pipe-separated, so a pipe
        # inside any spec field would silently split the line into the wrong parts.
        if "|" in prompt:
            raise SystemExit(f"'|' found in shot {shot['name']} — it breaks the jobs format")
        lines.append(f"{shot['name']} | {shot['size']} | {shot.get('count', 1)} | {prompt}")
    return lines


def main() -> int:
    if len(sys.argv) < 3:
        print("usage: python mkjobs.py <character.json> <out.txt>", file=sys.stderr)
        return 1
    spec = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    out = Path(sys.argv[2])
    # Written here rather than via shell redirect: on Windows, redirected stdout
    # uses the console codepage, which turned the em-dash in the hair description
    # into a replacement byte — mojibake that would have gone straight into every
    # prompt and broken any later verification of the locked blocks.
    out.write_text("\n".join(build(spec)) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(spec['shots'])} shots)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
